### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/api-client#1]
- [x] decide the public API
- [ ] add more contest parsers
- [ ] add more problem metadata parsers
- [ ] add tests for `oj-api` command (for command itself, not for parsers)
- [ ] add tests for parsers modules (import tests which are once removed due to the dependency to `oj`)
- [x] upload to PyPI

**Comment by kmyk** [comment]
とりあえず閉じておく
